CREATE TABLE "account" (
  "id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "name" VARCHAR(256) NOT NULL
)

CREATE TABLE "transaction" (
  "id" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  "created_at" TIMESTAMP(0) NOT NULL,
  "from" BIGINT NOT NULL,
  "to" BIGINT NOT NULL,
  "on" DATE NOT NULL,
  "amount" INT NOT NULL,
  "description" VARCHAR(256) NOT NULL
)
